services:
  mongo:
    image: mongo:8
    container_name: polylend-mongo
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped

  api:
    image: polylend-api
    container_name: polylend-api
    depends_on:
      - mongo
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017
    command: ['node', 'build/api.js']
    restart: unless-stopped

  listener:
    image: polylend-listener
    container_name: polylend-listener
    depends_on:
      - mongo
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017
      - RPC_URL=${RPC_URL}
      - WS_URL=${WS_URL}
    command: ['node', 'build/listener.js']
    restart: unless-stopped

  web-build:
    image: polylend-web-build
    build:
      context: ../webapp
      dockerfile: Dockerfile
      args:
        - VITE_PUBLIC_POSTHOG_PROJECT_TOKEN=${VITE_PUBLIC_POSTHOG_PROJECT_TOKEN}
        - VITE_PUBLIC_POSTHOG_HOST=${VITE_PUBLIC_POSTHOG_HOST}
    volumes:
      - web_dist:/web

  landing-build:
    image: polylend-landing-build
    build:
      context: ../landing
      dockerfile: Dockerfile
      args:
        - VITE_PUBLIC_POSTHOG_PROJECT_TOKEN=${VITE_PUBLIC_POSTHOG_PROJECT_TOKEN}
        - VITE_PUBLIC_POSTHOG_HOST=${VITE_PUBLIC_POSTHOG_HOST}
    volumes:
      - landing_dist:/landing

  caddy:
    image: caddy
    container_name: polylend-caddy
    depends_on:
      - web-build
      - landing-build
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - web_dist:/srv/web:ro
      - landing_dist:/srv/landing:ro
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  web_dist:
  landing_dist:
